FROM golang:alpine

RUN apk add git

RUN wget https://github.com/tailwindlabs/tailwindcss/releases/download/v3.3.3/tailwindcss-linux-x64 -O /usr/local/bin/tailwindcss

RUN chmod +x /usr/local/bin/tailwindcss